### PR TITLE
feat: discord rich presence

### PR DESCRIPTION
**Pull request by craftablescience**
Doesn't show the open filename or any private user data, just elapsed time and a link back to this GitHub repo

### CODE REVIEW

**Comment by HurricanePootis** [comment]
I am trying to compile vpkedit 4.1.3, I am getting the following error related to this new discord-rpc
```
In file included from /home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.cpp:1:
/home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.h:30:6: error: variable or field ‘setStartTimestamp’ declared void
   30 | void setStartTimestamp(std::int64_t time);
      |      ^~~~~~~~~~~~~~~~~
/home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.h:30:29: error: ‘int64_t’ is not a member of ‘std’; did you mean ‘int64_t’?
   30 | void setStartTimestamp(std::int64_t time);
      |                             ^~~~~~~
In file included from /usr/include/sys/types.h:155,
                 from /usr/include/stdlib.h:514,
                 from /usr/include/c++/13.2.1/cstdlib:79,
                 from /usr/include/c++/13.2.1/ext/string_conversions.h:43,
                 from /usr/include/c++/13.2.1/bits/basic_string.h:4097,
                 from /usr/include/c++/13.2.1/string:54,
                 from /home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.h:3:
/usr/include/bits/stdint-intn.h:27:19: note: ‘int64_t’ declared here
   27 | typedef __int64_t int64_t;
      |                   ^~~~~~~
/home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.h:32:6: error: variable or field ‘setEndTimestamp’ declared void
   32 | void setEndTimestamp(std::int64_t time);
      |      ^~~~~~~~~~~~~~~
/home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.h:32:27: error: ‘int64_t’ is not a member of ‘std’; did you mean ‘int64_t’?
   32 | void setEndTimestamp(std::int64_t time);
      |                           ^~~~~~~
/usr/include/bits/stdint-intn.h:27:19: note: ‘int64_t’ declared here
   27 | typedef __int64_t int64_t;
      |                   ^~~~~~~
/home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.cpp:18:6: error: ‘int64_t’ in namespace ‘std’ does not name a type
   18 | std::int64_t g_DiscordStartTimestamp = -1;
      |      ^~~~~~~
/home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.cpp:19:6: error: ‘int64_t’ in namespace ‘std’ does not name a type
   19 | std::int64_t g_DiscordEndTimestamp = -1;
      |      ^~~~~~~
/home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.cpp:77:6: error: variable or field ‘setStartTimestamp’ declared void
   77 | void DiscordPresence::setStartTimestamp(std::int64_t time) {
      |      ^~~~~~~~~~~~~~~
/home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.cpp:77:46: error: ‘int64_t’ is not a member of ‘std’; did you mean ‘int64_t’?
   77 | void DiscordPresence::setStartTimestamp(std::int64_t time) {
      |                                              ^~~~~~~
/usr/include/bits/stdint-intn.h:27:19: note: ‘int64_t’ declared here
   27 | typedef __int64_t int64_t;
      |                   ^~~~~~~
/home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.cpp:82:6: error: variable or field ‘setEndTimestamp’ declared void
   82 | void DiscordPresence::setEndTimestamp(std::int64_t time) {
      |      ^~~~~~~~~~~~~~~
/home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.cpp:82:44: error: ‘int64_t’ is not a member of ‘std’; did you mean ‘int64_t’?
   82 | void DiscordPresence::setEndTimestamp(std::int64_t time) {
      |                                            ^~~~~~~
/usr/include/bits/stdint-intn.h:27:19: note: ‘int64_t’ declared here
   27 | typedef __int64_t int64_t;
      |                   ^~~~~~~
/home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.cpp: In function ‘void DiscordPresence::update()’:
/home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.cpp:111:21: error: ‘g_DiscordStartTimestamp’ was not declared in this scope
  111 |                 if (g_DiscordStartTimestamp >= 0) {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~
/home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.cpp:114:21: error: ‘g_DiscordEndTimestamp’ was not declared in this scope
  114 |                 if (g_DiscordEndTimestamp >= 0) {
      |                     ^~~~~~~~~~~~~~~~~~~~~
/home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.cpp: In function ‘void DiscordPresence::reset()’:
/home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.cpp:158:9: error: ‘g_DiscordStartTimestamp’ was not declared in this scope
  158 |         g_DiscordStartTimestamp = -1;
      |         ^~~~~~~~~~~~~~~~~~~~~~~
/home/hurricane/aur/vpkedit/src/vpkedit/src/gui/utility/DiscordPresence.cpp:159:9: error: ‘g_DiscordEndTimestamp’ was not declared in this scope
  159 |         g_DiscordEndTimestamp = -1;
      |         ^~~~~~~~~~~~~~~~~~~~~
      ```

**Comment by craftablescience** [comment]
This looks like an easy fix, sorry you got that error. I wonder why CI compiled it fine

**Comment by craftablescience** [comment]
Let me know if that fixes it

**Comment by HurricanePootis** [comment]
It worked, thank u very much @craftablescience !!!

**Pull request merged**
