### PR TITLE
VPKEdit på SVENSKA

### PR DESCRIPTION
**Pull request by BreakinBenny**
pRaTaR DU sVeNsKa? (fall in scheweden)
image

### CODE REVIEW

**Comment by craftablescience** [comment]
I will tell you what I told the other guy, I use a website called POEditor for translations. Link is in the README. If you don't want to use it I will migrate the translations there myself.

**Comment by BreakinBenny** [comment]
> I will tell you what I told the other guy, I use a website called POEditor for translations. Link is in the README. If you don't want to use it I will migrate the translations there myself.

I'll get to it later this evening. ☺️

**Comment by craftablescience** [comment]
Thanks!

**Comment by BreakinBenny** [comment]
I've just tried joining the Swedish translation, it says new contributors aren't being accepted right now.

**Comment by BreakinBenny** [comment]
Feel free to when you have time!

**Comment by craftablescience** [comment]
Closing, these changes will be merged in manually and merging this PR would just be more effort

**Pull request closed without merging**
